apiVersion: v1
kind: Pod
metadata:
  annotations:
    app.kubernetes.io/instance: stacks-webapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: 0.0.107-cli-unit-tests
    applicationId: stacks/webapp-template
    applicationName: stacks-webapp
    customerID: amido
    owner: amido/stacks
    projectID: stacks
    role: web
    stage: devel
    tier: frontend
    version: 0.0.107-cli-unit-tests
  creationTimestamp: "2020-02-11T18:13:00Z"
  generateName: stacks-webapp-c6b8647d6-
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: stacks-webapp-template
    app.kubernetes.io/part-of: stacks
    environment: dev
    pod-template-hash: c6b8647d6
  name: stacks-webapp-c6b8647d6-8c4fw
  namespace: dev-stacks-web-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: stacks-webapp-c6b8647d6
    uid: 232267c5-4cfa-11ea-a57d-46461de51fe7
  resourceVersion: "8278636"
  selfLink: /api/v1/namespaces/dev-stacks-web-app/pods/stacks-webapp-c6b8647d6-8c4fw
  uid: 232da4e2-4cfa-11ea-a57d-46461de51fe7
spec:
  containers:
  - env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_ENV
      value: development
    - name: PORT
      value: "3000"
    - name: MENU_API_URL
      value: http://menuapi.dev-menu
    - name: LOG_LEVEL
      value: debug
    - name: APP_BASE_PATH
      value: '/web/stacks'
    - name: APP_BASE_URL
      value: http://dev.amidostacks.com
    - name: APPINSIGHTS_INSTRUMENTATIONKEY
      valueFrom:
        secretKeyRef:
          key: INSTRUMENTATIONKEY
          name: appinsights-dk698hhmb5
    image: amidouksstacksacrdev.azurecr.io/stacks-webapp:0.0.107-cli-unit-tests
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 25
    name: web
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 25
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-j7p8l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-default-35064155-vmss000000
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-j7p8l
    secret:
      defaultMode: 420
      secretName: default-token-j7p8l
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-11T18:13:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-11T18:14:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-11T18:14:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-11T18:13:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://73b22ea97bb87cb28258e73126bd138fd86fa90e825c5a244e9d3770bda24794
    image: amidouksstacksacrdev.azurecr.io/stacks-webapp:0.0.107-cli-unit-tests
    imageID: docker-pullable://amidouksstacksacrdev.azurecr.io/stacks-webapp@sha256:3fa5490d20cd2afb9f1c70c9ff890946ea0a375ea41003111411be6980d1bb7c
    lastState: {}
    name: web
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-02-11T18:13:58Z"
  hostIP: 172.16.0.4
  phase: Running
  podIP: 172.16.0.28
  qosClass: BestEffort
  startTime: "2020-02-11T18:13:00Z"
