using System;
using System.Threading.Tasks;
using Shouldly;
using System.Net.Http;
using xxAMIDOxx.xxSTACKSxx.E2E.Selenium.Api.Builders.Http;
using xxAMIDOxx.xxSTACKSxx.E2E.Selenium.Configuration;
using xxAMIDOxx.xxSTACKSxx.E2E.Selenium.Selenium;
using xxAMIDOxx.xxSTACKSxx.E2E.Selenium.Selenium.Components;

namespace xxAMIDOxx.xxSTACKSxx.E2E.Selenium.Tests.Steps
{
  public class CreateMenu
  {
    private readonly SeleniumWrapper user;
    private HttpResponseMessage response;
    private readonly ConfigModel config;
    private readonly string menuApiUrl;
    private const string menuPath = "v1/menu/";
    public string menuId;

    public CreateMenu(SeleniumWrapper seleniumWrapper)
    {
      user = seleniumWrapper;
      config = ConfigAccessor.GetApplicationConfiguration();
      menuApiUrl = config.MenuApiUrl;
    }

    #region Step Definitions

    #region Given
    public void ARestaurantWithMenus()
    {
      var menuListComponent = new MenuList(user.Instance());

      menuListComponent.Displayed(menuListComponent.menuList).ShouldBeTrue();
    }
    #endregion Given

    #region When
    public void ICreateANewMenu()
    {
      var header = new Header(user.Instance());
      var createMenu = new CreateForm(user.Instance());

      header.Click(header.createMenu);
      createMenu.Displayed(createMenu.name).ShouldBeTrue();

      createMenu.TypeText(createMenu.name, "Selenium Menu");
      createMenu.TypeText(createMenu.description, "Generated by .NET Selenium Framework");
      createMenu.Select(createMenu.active);
      createMenu.Click(createMenu.save);
    }
    #endregion When

    #region Then
    public void TheResturantShouldHaveANewMenu()
    {
      var snackbar = new Notifier(user.Instance());

      snackbar.Text(snackbar.message).ShouldContain("menu created");
      menuId = snackbar.Text(snackbar.message).Split(" ", 3)[0];
    }
    #endregion Then

    #region TearDown
    public async Task TearDownCreatedMenu()
    {
      response = await HttpRequestFactory.Delete(menuApiUrl, $"{menuPath}{menuId}");
      Console.WriteLine($"Successfully deleted menuId ={menuId}");
    }
    #endregion TearDown

    #endregion Step Definitions
  }
}
