apiVersion: v1
kind: Service
metadata:
  name: webapp_template
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: template
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: template
